// Code generated by protoc-gen-go. DO NOT EDIT.
// source: test.proto

package test

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Demo struct {
	Field1               string   `protobuf:"bytes,1,opt,name=field1,proto3" json:"field1,omitempty"`
	Field2               int32    `protobuf:"varint,2,opt,name=field2,proto3" json:"field2,omitempty"`
	Field3               []string `protobuf:"bytes,3,rep,name=field3,proto3" json:"field3,omitempty"`
	Field4               uint64   `protobuf:"varint,4,opt,name=field4,proto3" json:"field4,omitempty"`
	Field5               string   `protobuf:"bytes,5,opt,name=field5,proto3" json:"field5,omitempty"`
	Field6               string   `protobuf:"bytes,6,opt,name=field6,proto3" json:"field6,omitempty"`
	Field7               []byte   `protobuf:"bytes,7,opt,name=field7,proto3" json:"field7,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Demo) Reset()         { *m = Demo{} }
func (m *Demo) String() string { return proto.CompactTextString(m) }
func (*Demo) ProtoMessage()    {}
func (*Demo) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{0}
}

func (m *Demo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Demo.Unmarshal(m, b)
}
func (m *Demo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Demo.Marshal(b, m, deterministic)
}
func (m *Demo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Demo.Merge(m, src)
}
func (m *Demo) XXX_Size() int {
	return xxx_messageInfo_Demo.Size(m)
}
func (m *Demo) XXX_DiscardUnknown() {
	xxx_messageInfo_Demo.DiscardUnknown(m)
}

var xxx_messageInfo_Demo proto.InternalMessageInfo

func (m *Demo) GetField1() string {
	if m != nil {
		return m.Field1
	}
	return ""
}

func (m *Demo) GetField2() int32 {
	if m != nil {
		return m.Field2
	}
	return 0
}

func (m *Demo) GetField3() []string {
	if m != nil {
		return m.Field3
	}
	return nil
}

func (m *Demo) GetField4() uint64 {
	if m != nil {
		return m.Field4
	}
	return 0
}

func (m *Demo) GetField5() string {
	if m != nil {
		return m.Field5
	}
	return ""
}

func (m *Demo) GetField6() string {
	if m != nil {
		return m.Field6
	}
	return ""
}

func (m *Demo) GetField7() []byte {
	if m != nil {
		return m.Field7
	}
	return nil
}

func init() {
	proto.RegisterType((*Demo)(nil), "proto.test.Demo")
}

func init() { proto.RegisterFile("test.proto", fileDescriptor_c161fcfdc0c3ff1e) }

var fileDescriptor_c161fcfdc0c3ff1e = []byte{
	// 143 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x49, 0x2d, 0x2e,
	0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x02, 0x53, 0x7a, 0x20, 0x11, 0xa5, 0x75, 0x8c,
	0x5c, 0x2c, 0x2e, 0xa9, 0xb9, 0xf9, 0x42, 0x62, 0x5c, 0x6c, 0x69, 0x99, 0xa9, 0x39, 0x29, 0x86,
	0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x50, 0x1e, 0x5c, 0xdc, 0x48, 0x82, 0x49, 0x81, 0x51,
	0x83, 0x15, 0x2a, 0x6e, 0x04, 0x17, 0x37, 0x96, 0x60, 0x56, 0x60, 0x86, 0xab, 0x37, 0x86, 0x8b,
	0x9b, 0x48, 0xb0, 0x28, 0x30, 0x6a, 0xb0, 0x40, 0xc5, 0x4d, 0xe0, 0xe2, 0xa6, 0x12, 0xac, 0x48,
	0xe6, 0x9b, 0xc2, 0xc5, 0xcd, 0x24, 0xd8, 0x90, 0xc4, 0xcd, 0xe0, 0xe2, 0xe6, 0x12, 0xec, 0x0a,
	0x8c, 0x1a, 0x3c, 0x50, 0x71, 0x73, 0x27, 0xb6, 0x28, 0x16, 0x90, 0xc3, 0x93, 0xd8, 0xc0, 0x9e,
	0x30, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x27, 0xc9, 0xc8, 0x45, 0xd9, 0x00, 0x00, 0x00,
}
